[package]
name = "enr"
version = "0.1.0"
authors = ["Age Manning <Age@AgeManning.com>"]
edition = "2018"

[dependencies]
libp2p-core = { version = "0.8.0", path = "../../core" }
rlp = "0.3.0"
log = "0.4"
secp256k1 = "0.12.2"
sha3 = "0.8.2"

[dev-dependencies]
hex = "0.3.2"
